[project]
name = "programacion-para-no-programadores"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
